services:
  site1:
    image: nginx:alpine
    container_name: sn18_site1
    ports:
      - "8081:80"
    volumes:
      - ../sites/site1:/usr/share/nginx/html:ro
    networks:
      - web_multiuser_net
    restart: unless-stopped

  site2:
    image: nginx:alpine
    container_name: sn18_site2
    ports:
      - "8082:80"
    volumes:
      - ../sites/site2:/usr/share/nginx/html:ro
    networks:
      - web_multiuser_net
    restart: unless-stopped

networks:
  web_multiuser_net:
    driver: bridge
